### ISSUE TITLE
Sample Kit Attach times

### ISSUE THREAD

**Issue by blackearth2014** [JerrySievert/DrumKit#1]
Jerry,

I know the drum kit is a work in progress but the kick, snare and hats samples has an attach time issue. There seem to had space before the actual sample that needs to be truncated at the beginning or the module trigger inputs need to be adjusted.

Thanks
Omar

**Comment by JerrySievert** [comment]
there's a little bit of space in front of a couple of the samples.  I can do an audit and try to go from there.

I was trying to keep with the original samples provided, but if there are issues, I'm happy to edit - I wrote software to do the conversions for me, so it's not too much work :)

**Comment by blackearth2014** [comment]
Thanks

**Comment by JerrySievert** [comment]
closing as this was updated
