### ISSUE TITLE
Well....Could this have anything to do with Drumkit ?

### ISSUE THREAD

**Issue by Petervos2018** [JerrySievert/DrumKit#10]
The only plugin that was updated was yours....
After the update rack crashed and I got an error message : 

[1030.519 fatal src/main.cpp:39] Fatal signal 11. Stack trace:
33: ZN4rack10appDestroyEv 0x456435
32: gai_strerrorW 0x734800
31: _C_specific_handler 0x76f372fc
30: _chkstk 0x76f4bee0
29: RtlInitializeResource 0x76f1ff00
28: KiUserExceptionDispatcher 0x76f4b5f0
27: RtlFreeHeap 0x76f0a1c0
26: free 0xfe2b10ac
25: nsvgParseFromFile 0x474e51
24: ZN4rack6Window7loadSvgERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x45b96e
23: ZN12OpenHHWidgetC1EP12OpenHHModule 0x873bcdc
22: ZZN4rack11createModelI12OpenHHModule12OpenHHWidgetEEPNS_6plugin5ModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel18createModuleWidgetEv 0x874db10
21: ZN4rack3app10RackWidget11onDragHoverERKNS_5event9DragHoverE 0x48cf60
20: ZN4rack3app10RackWidget8fromJsonEP6json_t 0x48d680
19: ZN4rack12PatchManager8fromJsonEP6json_t 0x486e5a
18: ZN4rack12PatchManager4loadENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x487202
17: ZN4rack12PatchManager10loadDialogEv 0x48739a
16: ZN4rack2ui8MenuItem8doActionEv 0x4a443e
15: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
14: ZN4rack7updater17isUpdateAvailableEv 0x45914e
13: glfwPlatformUnlockMutex 0x4d732e
12: TranslateMessageEx 0x76cd97e0
11: CallWindowProcW 0x76cd3a04
10: CallWindowProcW 0x76cd3a04
9: glDebugEntry 0xf2fea170
8: TranslateMessageEx 0x76cd97e0
7: TranslateMessage 0x76cd95a8
6: glfwPlatformPollEvents 0x4da9a9
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x77c500
3: main 0x77c500
2: main 0x77c500
1: BaseThreadInitThunk 0x76dd5560
0: RtlUserThreadStart 0x76f33840

Any thing related to your modules ?

Greetz peter

**Comment by JerrySievert** [comment]
huh, the thread that it kicked in was parsing an svg component.

**Comment by Petervos2018** [comment]
Hey its all chinese to me ? 
Downgraded to 1.1.1. Drumkit and tried all sorts of things and could not get it to crash !

Greets Peter.

**Comment by JerrySievert** [comment]
maybe a corrupted unarchive when it installed?

**Comment by Petervos2018** [comment]
I tried again but still 1.1.2 gives me crashes and 1.1.1 does not. Sorry 

Latest crash : 
[96.272 fatal src/main.cpp:39] Fatal signal 11. Stack trace:
21: ZN4rack10appDestroyEv 0x456435
20: gai_strerrorW 0x734800
19: _C_specific_handler 0x76f372fc
18: _chkstk 0x76f4bee0
17: RtlInitializeResource 0x76f1ff00
16: KiUserExceptionDispatcher 0x76f4b5f0
15: ZN4rack6widget6Widget4stepEv 0x4a7bd2
14: ZN4rack6widget6Widget4stepEv 0x4a7bd2
13: ZN4rack6widget6Widget4stepEv 0x4a7bd2
12: ZN4rack6widget6Widget4stepEv 0x4a7bd2
11: ZN4rack6widget6Widget4stepEv 0x4a7bd2
10: ZN4rack6widget6Widget4stepEv 0x4a7bd2
9: ZN4rack2ui12ScrollWidget4stepEv 0x4a3aae
8: ZN4rack3app16RackScrollWidget4stepEv 0x48b9e0
7: ZN4rack6widget6Widget4stepEv 0x4a7bd2
6: ZN4rack3app5Scene4stepEv 0x4922e6
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x77c500
3: main 0x77c500
2: main 0x77c500
1: BaseThreadInitThunk 0x76dd5560
0: RtlUserThreadStart 0x76f33840

Has probably nothing to do with you.

Trouble shooting is hard.

**Comment by JerrySievert** [comment]
is there a list of modules you have loaded when it crashes?

**Comment by Petervos2018** [comment]
It's when I switch between 2 patches that it ( sometimes) crashes, and sometimes it clashes when I close rack , here are the 2 patches I switch between.

[Jerry S Drums - 28102019-VAR-FENCE-2.zip](https://github.com/JerrySievert/DrumKit/files/3799473/Jerry.S.Drums.-.28102019-VAR-FENCE-2.zip)

**Comment by JerrySievert** [comment]
I'm missing a couple of the modules you're using, let me get them added.

switching between those two otherwise is working flawlessly for me.  what operating system are you on?

**Comment by Petervos2018** [comment]
Windows 7 switching works but try closing after a switch.
I hate it when its not a simple do this and it crashes, 
but a sometimes when I do this that happens and sometimes it does not. :(

**Comment by JerrySievert** [comment]
added the new modules and still working fine for me - I'll leave this open for now though.

I can't run windows 7, just macOS, windows 10, and linux.

**Comment by Petervos2018** [comment]
Too bad it does not work out for me because the sequencer of 1.1.2 is doing exactly what I want, but I suspect its doing something else I don't like too... :(

Thanks for your time, I really appreciate it,

Peter.

**Comment by Petervos2018** [comment]
Closed after version 1.1.3 will open if problem remains/returns.

Thanks,

Peter.

**Comment by Petervos2018** [comment]
Well I'm on W10 now and 1.1.3. still gives me trouble, I'm staying at 1.1.1 for now.

**Comment by Petervos2018** [comment]
Keeping you posted,
just tried 1.1.4. and it crashed rack almost immediately back to 1.1.1.

**Comment by firolightfog** [comment]
Just for the record. As I mentioned in a private message as well as in [a forum topic](https://community.vcvrack.com/t/sv-drum-sequencer-testing-done/14693) I also face crashing of the DrumSeq with VCV Rack v1.1.6 under Win10. Almost(?) any of my patches can be crashed after multiple closing/opening/closing/opening/closing/opening/... of the VCV Rack application. The crashing happens right at one of the VCV Rack opening.

**Comment by JerrySievert** [comment]
I've sent a new version out to vcv for 2.0, just waiting on them.

not sure it will solve your problem (which I still can't reproduce), but worth a try.
