### ISSUE TITLE
Port to Rack v2?

### ISSUE THREAD

**Issue by NikolaiVChr** [JerrySievert/DrumKit#14]
I really like your Drum Sequencer.
Any plans to port it to Rack 2?

**Comment by JerrySievert** [comment]
yes, I just need to get the build team on it.  thanks for the reminder!

**Comment by NikolaiVChr** [comment]
Just changing the json might not be enough.
If I load up a patch with the drum sequencer in rack 2 (saved in rack 2) and then close Rack and open it again, then there is 50% chance Rack will crash. (windows 10)

**Comment by falkTX** [comment]
Crash is fixed with #16 
At least for the sequencer module.
