### ISSUE TITLE
v2: References to fonts stored across frames crashes VST

### ISSUE THREAD

**Issue by cschol** [JerrySievert/DrumKit#15]
References to fonts [cannot be stored across frames](https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames) in v2.

For example:

```
SmallTrackDisplay ( ) {
   value = NULL;
   font = APP->window->loadFont(asset::plugin(pluginInstance, "res/component/NovaMono.ttf"));
}
```

**Comment by JerrySievert** [comment]
fixed
