### ISSUE TITLE
DMX module does absolutely nothing

### ISSUE THREAD

**Issue by GBaige** [JerrySievert/DrumKit#18]
Tested on both Rack2Free and Cardinal. The DMX module produces no output whatsoever.

**Comment by JerrySievert** [comment]
odd, thanks for the report, I'll look into it!

**Comment by dromer** [comment]
Did you find the issue yet? I'm really wondering what this module sounds like now ;)

**Comment by XlosVSM** [comment]
Any update @JerrySievert ?
