### ISSUE TITLE
Kick Drums

### ISSUE THREAD

**Issue by ShofB** [JerrySievert/DrumKit#2]
All of the kicks seem to have the distorted drum sound.  It is easy to add distortion to a sample but impossible to take it away.  I think it would be better to have a selection of clean drums that the user could process if desired.

**Comment by JerrySievert** [comment]
hm. what os are you using?  they're clean for me in macOS, running at a max of -5/5.

**Comment by ShofB** [comment]
W10 with all of the latest updates.  Everything else is ok it's just there is distortion of all of the kick drum samples.

Shof B

My Web Site
http://www.l-and-l.net<http://www.l-and-l.net/>

Check out my Soundcloud stream @
https://soundcloud.com/shofb

And my YouTube MyKits demos @
http://www.youtube.com/channel/UCjKNiE1s2YlJYPsAKbe8vhg
________________________________

**Comment by JerrySievert** [comment]
I converted back to `wav`, and am seeing some clipping that didn't show up in the original convert.  I'll re-sample the bass drums while I work on the blank space issue.

**Comment by JerrySievert** [comment]
I dropped the levels on the bass drums, did a new release.  going to close this issue, feel free to reopen if it still distorts.
