### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by Coirt** [JerrySievert/DrumKit#6]
Hi Jerry get the following error on make. Win7

Followed build instructions:
```
$ git submodule init
$ git submodule update
$ make
```

```
src/controller/SBD.cpp: In constructor 'SBDModule::SBDModule()':
src/controller/SBD.cpp:6:38: error: 'time' was not declared in this scope
   noise = new SynthDevKit::PinkNoise(time(NULL));
                                      ^~~~
src/controller/SBD.cpp:6:38: note: suggested alternative: 'ftime'
   noise = new SynthDevKit::PinkNoise(time(NULL));
                                      ^~~~
                                      ftime
make: *** [../../compile.mk:62: build/src/controller/SBD.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by JerrySievert** [comment]
odd, nothing should have changed in `SBD.cpp` between 1.0 and 1.1 and I tested in macOS (clang++) and linux (g++) respectively.

I'll fire up a windows VM and see if I can reproduce.

**Comment by JerrySievert** [comment]
took a while to get windows up to date, but reproduced, added `#include <ctime>` and pushed an update.

**Comment by Coirt** [comment]
Had a feeling it might be something like that!

**Comment by JerrySievert** [comment]
still not sure why v1 compiled for windows - I went through the change history, and `ctime` was never an include for sbd :)

**Comment by Coirt** [comment]
Not sure might have been removed/included in common at some stage.

**Comment by Coirt** [comment]
@JerrySievert 
There's another quick fix needed "MarionetteBass" defined as the slug but in the .cpp it is defined as "Marionette" changing:
https://github.com/JerrySievert/DrumKit/blob/v1.0/src/view/Marionette.cpp#L113

to

`Model *modelMarionette = createModel<MarionetteModule, MarionetteWidget>("MarionetteBass");`

Fixes

**Comment by JerrySievert** [comment]
ha, that's what I get for changing the name at the last second.  fixed and pushed, thanks!
