### ISSUE TITLE
Windows 7 samples do not load

### ISSUE THREAD

**Issue by Coirt** [JerrySievert/DrumKit#7]
Just get an error for all samples:
`ERROR: cannot load file res/samples/....`

**Comment by JerrySievert** [comment]
oof what is it with windows :)

taking a look, thanks!

**Comment by JerrySievert** [comment]
wow, who knew that a flag that is explicitly ignored on every other platform for `fopen` is broken for windows if you don't include it?

**Comment by JerrySievert** [comment]
issue looks to be fixed in windows.
