### ISSUE TITLE
Reset on Drum Sequencer changes  01 seq

### ISSUE THREAD

**Issue by Petervos2018** [JerrySievert/DrumKit#8]
Try this : 
Bit hard to explain but draw a drum pattern on 01 go to 02 press reset and 01 will take the seq from 02.
Now clear 01 draw something in 02 press reset and 01 is the same as 02.

See what I mean ?

Greetings Peter.

**Comment by JerrySievert** [comment]
I'll give that a try - what's the state of "Cycle" when you do this?

**Comment by Petervos2018** [comment]
Cycle is on

**Comment by JerrySievert** [comment]
thanks.  I'll take a look in a couple of hours - on a roll with something else and don't want to get too distracted :)

**Comment by JerrySievert** [comment]
found and fixed.  I'll leave this open until the plugin manager is updated.

thanks for the report!

**Comment by JerrySievert** [comment]
and it's live!  please let me know if you continue to have issues - I'm going to close this now.
